"""add password_hash to identities

Revision ID: 44460b0bee7b
Revises: 442d5698b321
Create Date: 2025-12-18 22:50:39.539778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44460b0bee7b'
down_revision: Union[str, Sequence[str], None] = '442d5698b321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('password_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'password_hash')
    # ### end Alembic commands ###
